project_id = "fkeuexbcbtycdecruifd"

[functions.send-purchase-order-email]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.focus-nfe]
verify_jwt = false

[functions.ocr-danfe]
verify_jwt = false
